default: &default
  adapter: postgresql
  encoding: unicode
  username: satoshy
  password: satoshy
  pool: 5
  host: localhost


development:
  <<: *default
  database: skylink_development


test:
  <<: *default
  database: skylink_test

production:
  <<: *default
  database: skylink_production
  username: skylink
  password: <%= ENV['SKYLINK_DATABASE_PASSWORD'] %>
